version: "3.7"
services:
  db:
    image: postgres:11
    container_name: db_app
    volumes:
      - ./data:/app/data
    env_file:
      - .env-docker

  redis:
    image: redis:5
    container_name: redis_app

  app:
    build:
      context: .
    env_file:
      - .env-docker
    container_name: fastapi_app
    command: ["/app/docker/app.sh"]
    ports:
      - 9998:8000
    depends_on:
      - db
      - redis

  celery:
    build:
      context: .
    env_file:
      - .env-docker
    container_name: celery_app
    command: ["/app/docker/celery.sh"]
    depends_on:
      - redis

  flower:
    build:
      context: .
    env_file:
      - .env-docker
    container_name: flower_app
    command: ["/app/docker/flower.sh"]
    depends_on:
      - redis
      - celery
    ports:
      - 8888:5555